name: Sync Code

on:
  push:
    branches: ['master']

jobs:
  sync_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Set Up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Copy Code to B Repository
        run: |
          # GitHub Actions의 현재 작업 디렉토리 확인
          echo "Current working directory: $PWD"

          # git clone을 사용하여 다른 레포지토리를 복제
          git clone https://github.com/Kim-DaeHan/gitActionsTest.git /home/runner/gitActionsTest/

          # 복제한 레포지토리로 이동
          cd /home/runner/gitActionsTest/

          # 현재 작업 디렉토리에 있는 파일과 디렉토리를 복사
          cp -r $GITHUB_WORKSPACE/* ./

          # 변경사항을 추가하고 커밋
          git add .
          git commit -m "Sync code from Repository A"

          # 변경사항을 gitActionsTest 레포지토리로 푸시
          git push origin master
